# Generated by Django 4.1.7 on 2023-03-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('language', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
