# Generated by Django 4.1.7 on 2023-03-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='guide',
            name='lastname',
        ),
    ]
