# Generated by Django 4.1.7 on 2023-03-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_guide_image_remove_guide_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
